name: Pack builder
description: Build a container image using `pack`

inputs:
  image:
    required: false
    type: string
    default: ghcr.io/${{ github.repository }}:${{ github.sha }}
  path:
    required: false
    type: string
    default: "."
  runtime_release:
    required: false
    type: string
  builder:
    required: false
    type: string
    default: ""
  use_builder:
    required: false
    type: string
    default: "stable"
  buildpack:
    required: false
    type: string
    default: "heroku/python"
  build_env:
    required: false
    type: string
    default: ""
  runtime_env:
    required: false
    type: string
    default: ""
  run_safety_checks:
    required: false
    type: string
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Check config
      id: config
      shell: bash
      run: |
        if [ "${{ inputs.use_builder }}" == "upstream" ];
        then
          echo "Using upstream builder"
          echo "builder_image=heroku/builder:24" >> $GITHUB_OUTPUT
        elif [ "${{ inputs.use_builder }}" == "latest" ];
        then
          echo "Using latest builder"
          echo "builder_image=tools-harbor.wmcloud.org/toolforge/heroku-builder:24_0.21.5" >> $GITHUB_OUTPUT
        elif [ "${{ inputs.use_builder }}" == "stable" ];
        then
          echo "Using stable builder"
          echo "builder_image=tools-harbor.wmcloud.org/toolforge/heroku-builder:22" >> $GITHUB_OUTPUT
        elif [ "${{ inputs.use_builder }}" == "deprecated" ];
        then
          echo "Using deprecated builder"
          echo "builder_image=tools-harbor.wmcloud.org/toolforge/heroku-builder:22" >> $GITHUB_OUTPUT
          #echo "Deprecated builder has expired"
          #exit 1
        elif [ ! -z "${{ inputs.builder }}" ];
        then
          echo "Using custom builder: ${{ inputs.builder }}"
          echo "builder_image=${{ inputs.builder }}" >> $GITHUB_OUTPUT
        else
          echo "Unknown builder specified: ${{ inputs.use_builder }}"
          exit 1
        fi

    - name: Install pack
      shell: bash
      run: |
        sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
        sudo apt-get update
        sudo apt-get install -y pack-cli

    - name: Build image
      shell: bash
      run: |
        build_args=(
          "--builder" "${{ steps.config.outputs.builder_image }}"
          "--path" "${{ inputs.path }}"
        )
        
        if [ ! -z "${{ inputs.build_env }}" ];
        then
          while IFS= read -r build_env;
          do
            if [ ! -z "$build_env" ];
            then
              build_args+=("-e" "$build_env")
            fi
          done <<< "${{ inputs.build_env }}"
        fi

        # x-ref https://github.com/heroku/cnb-builder-images/blob/main/builder-24/builder.toml
        build_args+=(
          "--buildpack" "${{ inputs.buildpack }}"
        )
        if [ -f "${{ inputs.path }}/project.toml" ];
        then
          build_args+=("--buildpack" "heroku/deb-packages")
        fi
        if [ -f "${{ inputs.path }}/Procfile" ];
        then
          build_args+=("--buildpack" "heroku/procfile")
        fi

        # Future proof handling other vars
        # We only want to include the extra pack if the work is needed
        runtime_env_vars=()
        if [ ! -z "${{ inputs.runtime_release }}" ];
        then
          runtime_env_vars+=(-e "RUNTIME_ENVVAR_RELEASE_TAG=${{ inputs.runtime_release }}")
        fi
        
        if [ ! -z "${{ inputs.runtime_env }}" ];
        then
          while IFS= read -r runtime_env;
          do
            if [ ! -z "$runtime_env" ];
            then
              runtime_env_vars+=("-e" "$(echo "$runtime_env" | sed 's/^/RUNTIME_ENVVAR_/')")
            fi
          done <<< "${{ inputs.runtime_env }}"
        fi

        if [ ! -z "$runtime_env_vars" ];
        then
          build_args+=(
            "--buildpack" "https://github.com/InfraBits/envvar-buildpack/releases/download/v1.0.0/buildpack.tar.gz"
          )
          build_args+=("${runtime_env_vars[@]}")
        fi
        
        # Avoid set -x as it exposes secrets contained in inputs.build_args
        echo "Running pack for ${{ inputs.image }} with ${build_args[@]}"
        pack build "${{ inputs.image }}" "${build_args[@]}"

    - name: Scan image with trivy
      shell: bash
      run: |
        # Generic
        docker run -i \
        -v /var/run/docker.sock:/var/run/docker.sock \
        ghcr.io/aquasecurity/trivy image --scanners vuln "${{ inputs.image }}"

      if: inputs.run_safety_checks == 'true'
